"""`ProfileRegistry` — loads + indexes profiles from one or more roots.

Per §6.5, profiles ship in three layers (highest priority first):

  1. `<repo>/.sange/profiles/<category>/<name>.toml`
     Per-repo overrides + organization-specific profiles.
  2. `~/.sange/profiles/<category>/<name>.toml`
     Per-user overrides.
  3. `templates/gitignore-profiles/<category>/<name>.toml`
     Sange-shipped defaults (the 35-profile registry generated by T-G-015).

A profile defined in (1) shadows one with the same name in (2) or (3).
The registry resolves shadowing at load time; the composition layer
(`compose.py`) sees only the winners.
"""

from __future__ import annotations

from dataclasses import dataclass, field
from pathlib import Path

from sange.core.gitignore.profile import Profile, ProfileError, load_profile


@dataclass(frozen=True)
class RegistryLoad:
    """Detail about a single registry-load pass.

    Useful for diagnostics + tests: which root supplied each
    profile, which files were skipped (and why), how many shadows
    happened.
    """

    by_name: dict[str, Profile] = field(default_factory=dict)
    shadowed: list[tuple[str, Path, Path]] = field(default_factory=list)
    skipped: list[tuple[Path, str]] = field(default_factory=list)


class ProfileRegistry:
    """Indexed view over the loadable profiles in a set of root directories.

    Roots are searched in priority order (highest first); a name
    defined in a higher-priority root shadows lower-priority entries
    with the same name.

    Construction is eager — every TOML under each root is parsed at
    `ProfileRegistry(...)` time. Errors in any single file are
    recorded in `load_detail.skipped` rather than raised, so a bad
    profile doesn't poison the whole registry. Callers can inspect
    `load_detail.skipped` to surface diagnostics.
    """

    def __init__(self, roots: list[Path]) -> None:
        self._roots = [Path(r) for r in roots]
        self._load_detail = RegistryLoad()
        self._load_all()

    # ---- public surface ------------------------------------------- #

    @property
    def roots(self) -> tuple[Path, ...]:
        return tuple(self._roots)

    @property
    def load_detail(self) -> RegistryLoad:
        return self._load_detail

    def get(self, name: str) -> Profile:
        """Return the profile named `name`; raise if not found."""

        try:
            return self._load_detail.by_name[name]
        except KeyError as exc:
            raise ProfileError(
                f"profile not found: {name!r} (known: "
                f"{', '.join(sorted(self._load_detail.by_name)) or '<empty>'})"
            ) from exc

    def has(self, name: str) -> bool:
        return name in self._load_detail.by_name

    def all_profiles(self) -> tuple[Profile, ...]:
        """All loaded profiles, sorted by name."""

        return tuple(
            sorted(self._load_detail.by_name.values(), key=lambda p: p.name)
        )

    def all_names(self) -> tuple[str, ...]:
        return tuple(sorted(self._load_detail.by_name))

    def by_category(self, category: str) -> tuple[Profile, ...]:
        return tuple(
            sorted(
                (p for p in self._load_detail.by_name.values() if p.category == category),
                key=lambda p: p.name,
            )
        )

    def resolve_extends_chain(self, name: str) -> tuple[Profile, ...]:
        """Return the full extends chain for `name`, ancestors first.

        Order: deepest ancestor first → … → direct parents → `name`
        itself last. The chain is duplicate-free (a diamond hierarchy
        only emits each ancestor once, in its first-seen position).

        Raises `ProfileError` if a cycle is detected.
        """

        chain: list[Profile] = []
        seen: set[str] = set()
        in_progress: set[str] = set()
        self._dfs_extends(name, chain, seen, in_progress)
        return tuple(chain)

    # ---- internals ------------------------------------------------ #

    def _dfs_extends(
        self,
        name: str,
        chain: list[Profile],
        seen: set[str],
        in_progress: set[str],
    ) -> None:
        if name in seen:
            return
        if name in in_progress:
            raise ProfileError(
                f"profile extends-chain cycle detected at {name!r}"
            )
        prof = self.get(name)
        in_progress.add(name)
        for parent in prof.extends:
            self._dfs_extends(parent, chain, seen, in_progress)
        in_progress.remove(name)
        chain.append(prof)
        seen.add(name)

    def _load_all(self) -> None:
        # Walk roots in priority order. A name seen later in the loop
        # (i.e. from a lower-priority root) is skipped + recorded.
        for root in self._roots:
            if not root.is_dir():
                continue
            for path in sorted(root.rglob("*.toml")):
                if not path.is_file():
                    continue
                try:
                    profile = load_profile(path)
                except ProfileError as exc:
                    self._load_detail.skipped.append((path, str(exc)))
                    continue
                existing = self._load_detail.by_name.get(profile.name)
                if existing is not None:
                    # First-seen wins (highest priority).
                    self._load_detail.shadowed.append(
                        (profile.name, existing.source_path, path)
                    )
                    continue
                self._load_detail.by_name[profile.name] = profile


def default_registry_roots(repo_root: Path | None = None) -> list[Path]:
    """Build the canonical three-tier root list.

    Priority (first = highest):
      1. `<repo_root>/.sange/profiles/`        (if repo_root supplied)
      2. `~/.sange/profiles/`
      3. `<sange-install>/templates/gitignore-profiles/`
    """

    roots: list[Path] = []
    if repo_root is not None:
        roots.append(Path(repo_root).resolve() / ".sange" / "profiles")
    home = Path.home()
    roots.append(home / ".sange" / "profiles")
    # The shipped templates live alongside the source tree. Walk up
    # from this file's location to find the repo root + templates/.
    here = Path(__file__).resolve()
    # core/gitignore/registry.py → core/gitignore → core → sange → src → <repo>
    pkg_root = here.parent.parent.parent.parent.parent
    roots.append(pkg_root / "templates" / "gitignore-profiles")
    return roots


__all__ = [
    "ProfileRegistry",
    "RegistryLoad",
    "default_registry_roots",
]
