# vcs/git.mk — delegates git-* targets to the `sange` CLI.
# Generated by tools/generators/makefile_kit.py (T-012).
# Targets use `-` separator (not `:`) because GNU Make's recipe parser
# treats unescaped colons as rule-delimiters and escaping is awkward
# inside the auto-help awk pipeline.

.PHONY: git-status git-log git-commit

git-status: ## Show working tree status
	@sange git status

git-log: ## Show recent commits
	@sange git log

git-commit: ## Generate a Conventional Commits message from staged diff
	@git diff --staged | sange commit
