# lang/python.mk — test / lint / format / install targets.
# Generated by tools/generators/makefile_kit.py (T-012).
# Requires _core/env.mk (PYTHON variable) loaded first.

.PHONY: python-install python-test python-lint python-format python-typecheck

python-install: ## Install package + dev extras
	@$(PYTHON) -m pip install -e ".[dev]"

python-test: ## Run pytest
	@$(PYTHON) -m pytest

python-lint: ## Run ruff
	@$(PYTHON) -m ruff check .

python-format: ## Format code with ruff
	@$(PYTHON) -m ruff format .

python-typecheck: ## Run mypy
	@$(PYTHON) -m mypy src
