# _core/colors.mk — terminal-color echo helpers.
# Generated by tools/generators/makefile_kit.py (T-012).
# Disabled when stdout is not a TTY (NO_COLOR or CI env vars also kill colors).

ifeq ($(NO_COLOR),)
ifneq ($(CI),true)
ifeq ($(MAKE_TERMOUT),)
COLOR_BLUE   := \033[34m
COLOR_GREEN  := \033[32m
COLOR_YELLOW := \033[33m
COLOR_RED    := \033[31m
COLOR_BOLD   := \033[1m
COLOR_RESET  := \033[0m
endif
endif
endif
