# _core/env.mk — SANGE_ROOT, OS detection, common variables.
# Generated by tools/generators/makefile_kit.py (T-012).

SANGE_ROOT ?= $(CURDIR)

UNAME_S := $(shell uname -s 2>/dev/null || echo Windows)
IS_LINUX := $(if $(filter Linux,$(UNAME_S)),1,)
IS_MACOS := $(if $(filter Darwin,$(UNAME_S)),1,)
IS_WINDOWS := $(if $(filter Windows%,$(UNAME_S)),1,)

UNAME_M := $(shell uname -m 2>/dev/null || echo x86_64)
IS_ARM64 := $(if $(filter arm64 aarch64,$(UNAME_M)),1,)
IS_AMD64 := $(if $(filter x86_64 amd64,$(UNAME_M)),1,)

# Python interpreter resolution (per ADR-019 prefer venv).
PYTHON ?= python3
