# _core/help.mk — auto-help target parsing `## description` markers.
# Generated by tools/generators/makefile_kit.py (T-012).
# Per §10.2: each target line followed by a `## ...` comment is shown
# in `make help` output.

.PHONY: help

help: ## Show available targets
	@awk 'BEGIN {FS = ":.*?## "} \
		/^[a-zA-Z0-9_-]+:.*?## / { \
			printf "  \033[36m%-24s\033[0m %s\n", $$1, $$2 \
		}' $(MAKEFILE_LIST) | sort
