"""Generate the modular Makefile kit — §10.

T-012 — emits the v0.1 starter library of fragments under
`templates/makefiles/` plus a top-level `templates/Makefile.template`
shim. Per §10.1 the shim is a thin include statement set:

  include .sange/makefiles/_core/*.mk
  include .sange/makefiles/<category>/*.mk
  ...
  -include .sange/makefiles/_local/*.mk

Per §10.2 fragments are organized by category. v0.1 ships:

  * `_core/help.mk`    — auto-help target parsing `## description` markers.
  * `_core/env.mk`     — SANGE_ROOT, OS detection, common variables.
  * `_core/colors.mk`  — terminal-color echo helpers.
  * `vcs/git.mk`       — delegates `git:*` targets to `sange`.
  * `lang/python.mk`   — test/lint/format/install targets.

Each fragment is **self-documenting** per §10.2: every target has a
`## description` comment that `_core/help.mk` parses. The shim itself
is regenerated on `sange init` (the future scaffold command will run
this generator).

Per §10.3 the shim is gitignored — adding it via `sange doctor`'s
Makefile-tracked detection is T-013. T-012 only emits the artifacts;
their installation into a target repo is `sange scaffold`'s job.

Frontmatter convention: comment-prefixed header (4 lines max) per
the `profile_registry.py` precedent. The kit_manifest.py (T-G-005)
captures byte-level sha256 of every templates/ file, so manual edits
are detected at the kit-trust-root layer regardless of per-file
frontmatter.
"""

from __future__ import annotations

import datetime as _dt
import sys
from dataclasses import dataclass
from pathlib import Path

# --- Path bootstrap ------------------------------------------------------- #
HERE = Path(__file__).resolve().parent
REPO_ROOT = HERE.parent.parent
SRC_DIR = REPO_ROOT / "src"

if str(SRC_DIR) not in sys.path:
    sys.path.insert(0, str(SRC_DIR))
if str(HERE) not in sys.path:
    sys.path.insert(0, str(HERE))

# --- Imports -------------------------------------------------------------- #
from _lib.output import (  # noqa: E402
    WriteMode,
    WriteOutcome,
    VerificationResult,
)


GENERATOR_VERSION = "1.0.0"
GENERATED_BY = "tools/generators/makefile_kit.py"
TEMPLATES_DIR = REPO_ROOT / "templates"
MAKEFILES_DIR = TEMPLATES_DIR / "makefiles"
SHIM_PATH = TEMPLATES_DIR / "Makefile.template"


# --------------------------------------------------------------------------- #
# Fragment content
# --------------------------------------------------------------------------- #


# Canonical category load order per §10.1. Adding a category requires
# an ADR + this list updated in lock-step.
CATEGORY_ORDER: tuple[str, ...] = (
    "ai", "ci", "db", "framework", "infra", "lang", "release", "security", "vcs",
)


_SHIM = """\
# Auto-generated by Sange. Do not edit. Do not commit.
# Source: tools/generators/makefile_kit.py (T-012). Regenerate via
# `python tools/generators/all.py --only T-012 --write`.
#
# Load order per §10.1: _core/ first, then categories alphabetical,
# then _local/ last. Every category line uses `-include` so make
# tolerates absent directories — kits ship partial categories until
# v1.0; missing categories are not an error.

-include .sange/makefiles/_core/*.mk
-include .sange/makefiles/ai/*.mk
-include .sange/makefiles/ci/*.mk
-include .sange/makefiles/db/*.mk
-include .sange/makefiles/framework/*.mk
-include .sange/makefiles/infra/*.mk
-include .sange/makefiles/lang/*.mk
-include .sange/makefiles/release/*.mk
-include .sange/makefiles/security/*.mk
-include .sange/makefiles/vcs/*.mk
-include .sange/makefiles/_local/*.mk

.DEFAULT_GOAL := help
"""


_CORE_HELP = """\
# _core/help.mk — auto-help target parsing `## description` markers.
# Generated by tools/generators/makefile_kit.py (T-012).
# Per §10.2: each target line followed by a `## ...` comment is shown
# in `make help` output.

.PHONY: help

help: ## Show available targets
\t@awk 'BEGIN {FS = ":.*?## "} \\
\t\t/^[a-zA-Z0-9_-]+:.*?## / { \\
\t\t\tprintf "  \\033[36m%-24s\\033[0m %s\\n", $$1, $$2 \\
\t\t}' $(MAKEFILE_LIST) | sort
"""


_CORE_ENV = """\
# _core/env.mk — SANGE_ROOT, OS detection, common variables.
# Generated by tools/generators/makefile_kit.py (T-012).

SANGE_ROOT ?= $(CURDIR)

UNAME_S := $(shell uname -s 2>/dev/null || echo Windows)
IS_LINUX := $(if $(filter Linux,$(UNAME_S)),1,)
IS_MACOS := $(if $(filter Darwin,$(UNAME_S)),1,)
IS_WINDOWS := $(if $(filter Windows%,$(UNAME_S)),1,)

UNAME_M := $(shell uname -m 2>/dev/null || echo x86_64)
IS_ARM64 := $(if $(filter arm64 aarch64,$(UNAME_M)),1,)
IS_AMD64 := $(if $(filter x86_64 amd64,$(UNAME_M)),1,)

# Python interpreter resolution (per ADR-019 prefer venv).
PYTHON ?= python3
"""


_CORE_COLORS = """\
# _core/colors.mk — terminal-color echo helpers.
# Generated by tools/generators/makefile_kit.py (T-012).
# Disabled when stdout is not a TTY (NO_COLOR or CI env vars also kill colors).

ifeq ($(NO_COLOR),)
ifneq ($(CI),true)
ifeq ($(MAKE_TERMOUT),)
COLOR_BLUE   := \\033[34m
COLOR_GREEN  := \\033[32m
COLOR_YELLOW := \\033[33m
COLOR_RED    := \\033[31m
COLOR_BOLD   := \\033[1m
COLOR_RESET  := \\033[0m
endif
endif
endif
"""


_VCS_GIT = """\
# vcs/git.mk — delegates git-* targets to the `sange` CLI.
# Generated by tools/generators/makefile_kit.py (T-012).
# Targets use `-` separator (not `:`) because GNU Make's recipe parser
# treats unescaped colons as rule-delimiters and escaping is awkward
# inside the auto-help awk pipeline.

.PHONY: git-status git-log git-commit

git-status: ## Show working tree status
\t@sange git status

git-log: ## Show recent commits
\t@sange git log

git-commit: ## Generate a Conventional Commits message from staged diff
\t@git diff --staged | sange commit
"""


_LANG_PYTHON = """\
# lang/python.mk — test / lint / format / install targets.
# Generated by tools/generators/makefile_kit.py (T-012).
# Requires _core/env.mk (PYTHON variable) loaded first.

.PHONY: python-install python-test python-lint python-format python-typecheck

python-install: ## Install package + dev extras
\t@$(PYTHON) -m pip install -e ".[dev]"

python-test: ## Run pytest
\t@$(PYTHON) -m pytest

python-lint: ## Run ruff
\t@$(PYTHON) -m ruff check .

python-format: ## Format code with ruff
\t@$(PYTHON) -m ruff format .

python-typecheck: ## Run mypy
\t@$(PYTHON) -m mypy src
"""


@dataclass(frozen=True)
class _Fragment:
    category: str
    name: str
    content: str

    @property
    def path(self) -> Path:
        return MAKEFILES_DIR / self.category / f"{self.name}.mk"


FRAGMENTS: tuple[_Fragment, ...] = (
    _Fragment(category="_core", name="help", content=_CORE_HELP),
    _Fragment(category="_core", name="env", content=_CORE_ENV),
    _Fragment(category="_core", name="colors", content=_CORE_COLORS),
    _Fragment(category="vcs", name="git", content=_VCS_GIT),
    _Fragment(category="lang", name="python", content=_LANG_PYTHON),
)


# --------------------------------------------------------------------------- #
# Atomic write (mirrors _lib/output._atomic_write but emits plain bytes)
# --------------------------------------------------------------------------- #


def _atomic_write(path: Path, content: str) -> None:
    """Write `content` to `path` via tmp + rename."""

    import tempfile

    path.parent.mkdir(parents=True, exist_ok=True)
    fd, tmp_name = tempfile.mkstemp(
        dir=str(path.parent),
        prefix=f".{path.name}.",
        suffix=".tmp",
    )
    try:
        import os as _os

        with _os.fdopen(fd, "w", encoding="utf-8") as handle:
            handle.write(content)
            handle.flush()
            _os.fsync(handle.fileno())
        _os.replace(tmp_name, path)
    except Exception:
        try:
            Path(tmp_name).unlink()
        except OSError:
            pass
        raise


def _emit(path: Path, content: str, mode: WriteMode) -> WriteOutcome:
    from _lib import fingerprint

    canonical = content if content.endswith("\n") else content + "\n"
    out_sha = fingerprint.sha256_text(canonical)
    if mode is WriteMode.WRITE:
        _atomic_write(path, canonical)
        return WriteOutcome(
            path=path, mode=mode, output_sha256=out_sha, result=None
        )
    # CHECK mode: compare byte-exact content (no frontmatter to strip).
    if not path.is_file():
        return WriteOutcome(
            path=path,
            mode=mode,
            output_sha256=out_sha,
            result=VerificationResult.MISSING,
        )
    existing = path.read_text(encoding="utf-8")
    result = (
        VerificationResult.MATCH if existing == canonical
        else VerificationResult.MISMATCH
    )
    return WriteOutcome(
        path=path, mode=mode, output_sha256=out_sha, result=result
    )


# --------------------------------------------------------------------------- #
# Entry-point
# --------------------------------------------------------------------------- #


def run(
    *,
    mode: WriteMode,
    clock: _dt.datetime,  # noqa: ARG001 — clock unused (no frontmatter timestamps)
) -> list[WriteOutcome]:
    """Emit the shim + every fragment. Idempotent in WRITE mode."""

    outcomes: list[WriteOutcome] = []

    # Shim first.
    outcomes.append(_emit(SHIM_PATH, _SHIM, mode))

    # Then each fragment.
    for frag in FRAGMENTS:
        outcomes.append(_emit(frag.path, frag.content, mode))

    return outcomes


if __name__ == "__main__":
    import argparse

    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--write", action="store_true", help="Write the files.")
    parser.add_argument("--check", action="store_true", help="Verify on-disk content.")
    args = parser.parse_args()

    if not (args.write or args.check):
        args.write = True
    mode = WriteMode.WRITE if args.write else WriteMode.CHECK

    results = run(mode=mode, clock=_dt.datetime.now(tz=_dt.timezone.utc))
    rc = 0
    for r in results:
        if r.result is not None and r.result.value != "match":
            rc = 66
        line = f"[{mode.value}] {r.path}  sha256={r.output_sha256[:16]}"
        if r.result is not None:
            line += f"  ({r.result.value})"
        print(line)
    raise SystemExit(rc)
