"""Tests for tools/generators/makefile_kit.py — T-012."""

from __future__ import annotations

import datetime as _dt
import shutil
import subprocess
import sys
from pathlib import Path

import pytest

REPO_ROOT = Path(__file__).resolve().parents[2]
GENERATORS_DIR = REPO_ROOT / "tools" / "generators"
SRC_DIR = REPO_ROOT / "src"
for p in (str(SRC_DIR), str(GENERATORS_DIR)):
    if p not in sys.path:
        sys.path.insert(0, p)

from _lib.output import VerificationResult, WriteMode  # noqa: E402
from makefile_kit import (  # noqa: E402
    CATEGORY_ORDER,
    FRAGMENTS,
    MAKEFILES_DIR,
    SHIM_PATH,
    _CORE_COLORS,
    _CORE_ENV,
    _CORE_HELP,
    _LANG_PYTHON,
    _SHIM,
    _VCS_GIT,
    run,
)


_FIXED_CLOCK = _dt.datetime(2026, 5, 14, 12, 0, 0, tzinfo=_dt.timezone.utc)


# --------------------------------------------------------------------------- #
# Content sanity
# --------------------------------------------------------------------------- #


class TestShim:
    def test_starts_with_auto_generated_marker(self) -> None:
        assert _SHIM.startswith("# Auto-generated by Sange")

    def test_includes_all_categories(self) -> None:
        for cat in CATEGORY_ORDER:
            assert f"-include .sange/makefiles/{cat}/*.mk" in _SHIM

    def test_includes_core_first(self) -> None:
        # _core must appear before any category.
        core_idx = _SHIM.find("_core/*.mk")
        for cat in CATEGORY_ORDER:
            cat_idx = _SHIM.find(f"{cat}/*.mk")
            assert core_idx < cat_idx, f"{cat} must follow _core"

    def test_local_last_and_tolerant(self) -> None:
        # _local must use -include (leading dash) AND be the last include.
        lines = [
            line for line in _SHIM.splitlines() if "include " in line
        ]
        last_include = lines[-1]
        assert "_local" in last_include
        assert last_include.lstrip().startswith("-include")

    def test_default_goal_is_help(self) -> None:
        assert ".DEFAULT_GOAL := help" in _SHIM


class TestCoreHelp:
    def test_has_help_target(self) -> None:
        assert "help: ## " in _CORE_HELP

    def test_awk_present(self) -> None:
        assert "awk" in _CORE_HELP

    def test_phony_declared(self) -> None:
        assert ".PHONY: help" in _CORE_HELP


class TestCoreEnv:
    def test_sange_root(self) -> None:
        assert "SANGE_ROOT" in _CORE_ENV

    def test_os_detection(self) -> None:
        assert "IS_LINUX" in _CORE_ENV
        assert "IS_MACOS" in _CORE_ENV
        assert "IS_WINDOWS" in _CORE_ENV

    def test_arch_detection(self) -> None:
        assert "IS_ARM64" in _CORE_ENV
        assert "IS_AMD64" in _CORE_ENV

    def test_python_default(self) -> None:
        assert "PYTHON ?= python3" in _CORE_ENV


class TestCoreColors:
    def test_no_color_env_check(self) -> None:
        assert "NO_COLOR" in _CORE_COLORS

    def test_ci_env_check(self) -> None:
        assert "$(CI)" in _CORE_COLORS

    def test_color_constants(self) -> None:
        for c in ("COLOR_GREEN", "COLOR_RED", "COLOR_RESET"):
            assert c in _CORE_COLORS


class TestVcsGit:
    def test_targets(self) -> None:
        for t in ("git-status", "git-log", "git-commit"):
            assert f"{t}: ## " in _VCS_GIT

    def test_delegates_to_sange(self) -> None:
        assert "@sange git status" in _VCS_GIT
        assert "sange commit" in _VCS_GIT

    def test_phony_declared(self) -> None:
        assert ".PHONY: git-status git-log git-commit" in _VCS_GIT


class TestLangPython:
    def test_targets(self) -> None:
        for t in (
            "python-install", "python-test", "python-lint",
            "python-format", "python-typecheck",
        ):
            assert f"{t}: ## " in _LANG_PYTHON

    def test_uses_python_variable(self) -> None:
        assert "$(PYTHON)" in _LANG_PYTHON


# --------------------------------------------------------------------------- #
# Category order — invariant
# --------------------------------------------------------------------------- #


class TestCategoryOrder:
    def test_alphabetical(self) -> None:
        assert list(CATEGORY_ORDER) == sorted(CATEGORY_ORDER)

    def test_no_core_no_local(self) -> None:
        # _core + _local are special-cased — not in CATEGORY_ORDER.
        assert "_core" not in CATEGORY_ORDER
        assert "_local" not in CATEGORY_ORDER


# --------------------------------------------------------------------------- #
# Fragment inventory
# --------------------------------------------------------------------------- #


class TestFragments:
    def test_fragment_count(self) -> None:
        # v0.1 ships 5 fragments: 3 _core + 1 vcs + 1 lang.
        assert len(FRAGMENTS) == 5

    def test_every_fragment_has_content(self) -> None:
        for frag in FRAGMENTS:
            assert frag.content
            assert len(frag.content) > 100  # non-trivial

    def test_every_fragment_has_generator_attribution(self) -> None:
        for frag in FRAGMENTS:
            assert "tools/generators/makefile_kit.py" in frag.content


# --------------------------------------------------------------------------- #
# Generator entry-point
# --------------------------------------------------------------------------- #


class TestRun:
    def test_write_creates_all_files(self, tmp_path: Path) -> None:
        # Redirect MAKEFILES_DIR + SHIM_PATH to tmp_path for the test.
        from makefile_kit import (
            _Fragment as Fragment,  # noqa: F401
        )

        # Save originals.
        import makefile_kit

        original_mk_dir = makefile_kit.MAKEFILES_DIR
        original_shim = makefile_kit.SHIM_PATH
        # Also reroute every fragment.path via monkey-patching the
        # MAKEFILES_DIR module attribute. Because Fragment is frozen,
        # we replace FRAGMENTS with rerouted copies temporarily.

        try:
            makefile_kit.MAKEFILES_DIR = tmp_path / "makefiles"
            makefile_kit.SHIM_PATH = tmp_path / "Makefile.template"

            # FRAGMENTS' .path property reads makefile_kit.MAKEFILES_DIR at
            # access time? No — it's a @property on the dataclass; let me
            # check. Actually it returns MAKEFILES_DIR / ... at call time
            # because MAKEFILES_DIR is a module-level name. Re-read.
            outcomes = run(mode=WriteMode.WRITE, clock=_FIXED_CLOCK)
            assert len(outcomes) == 6  # 1 shim + 5 fragments

            assert (tmp_path / "Makefile.template").is_file()
            for frag in FRAGMENTS:
                assert frag.path.is_file()
        finally:
            makefile_kit.MAKEFILES_DIR = original_mk_dir
            makefile_kit.SHIM_PATH = original_shim

    def test_check_matches_after_write(self) -> None:
        """Run WRITE then CHECK on the real templates/ dir; CHECK must
        report 'match' for every outcome."""

        write_results = run(mode=WriteMode.WRITE, clock=_FIXED_CLOCK)
        check_results = run(mode=WriteMode.CHECK, clock=_FIXED_CLOCK)
        for outcome in check_results:
            assert outcome.result is VerificationResult.MATCH, (
                f"{outcome.path} did not match after write"
            )

    def test_idempotent_writes(self) -> None:
        """Two consecutive WRITE runs produce identical file content."""

        results_a = run(mode=WriteMode.WRITE, clock=_FIXED_CLOCK)
        results_b = run(mode=WriteMode.WRITE, clock=_FIXED_CLOCK)
        # The output_sha256 of each file must match across the two runs.
        for a, b in zip(results_a, results_b, strict=True):
            assert a.output_sha256 == b.output_sha256


# --------------------------------------------------------------------------- #
# Live `make` integration — only runs if `make` is on PATH.
# --------------------------------------------------------------------------- #


_MAKE = shutil.which("make")


@pytest.mark.skipif(_MAKE is None, reason="make not on PATH")
class TestRealMake:
    def _setup_kit(self, tmp_path: Path) -> Path:
        target = tmp_path / "kit-test"
        target.mkdir()
        makefiles_target = target / ".sange" / "makefiles"
        makefiles_target.mkdir(parents=True)
        # Copy live emitted files (we just wrote them in the previous
        # test class).
        for frag in FRAGMENTS:
            dest = makefiles_target / frag.category / f"{frag.name}.mk"
            dest.parent.mkdir(parents=True, exist_ok=True)
            shutil.copy(frag.path, dest)
        shutil.copy(SHIM_PATH, target / "Makefile")
        return target

    def test_make_help_succeeds(self, tmp_path: Path) -> None:
        target = self._setup_kit(tmp_path)
        result = subprocess.run(
            [_MAKE, "help"],
            cwd=str(target),
            capture_output=True,
            text=True,
            timeout=10,
        )
        assert result.returncode == 0, (
            f"make help failed: stdout={result.stdout!r} stderr={result.stderr!r}"
        )

    def test_make_help_lists_known_targets(self, tmp_path: Path) -> None:
        target = self._setup_kit(tmp_path)
        result = subprocess.run(
            [_MAKE, "help"],
            cwd=str(target),
            capture_output=True,
            text=True,
            timeout=10,
        )
        # Strip ANSI codes for a clean substring check.
        import re
        plain = re.sub(r"\x1b\[[0-9;]*m", "", result.stdout)
        for expected in (
            "help", "git-status", "git-log", "git-commit",
            "python-test", "python-lint",
        ):
            assert expected in plain, f"missing {expected!r} in help output"

    def test_make_help_default_target(self, tmp_path: Path) -> None:
        """No args = help (per `.DEFAULT_GOAL := help`)."""

        target = self._setup_kit(tmp_path)
        result = subprocess.run(
            [_MAKE], cwd=str(target), capture_output=True, text=True, timeout=10,
        )
        assert result.returncode == 0
        assert "help" in result.stdout.lower() or "Show available targets" in result.stdout
