"""Tests for src/sange/cli/init.py — `sange init`."""

from __future__ import annotations

import json
from pathlib import Path

import pytest
from typer.testing import CliRunner

from sange.cli import app


@pytest.fixture
def runner() -> CliRunner:
    return CliRunner()


# --------------------------------------------------------------------------- #
# Fresh init
# --------------------------------------------------------------------------- #


class TestFreshInit:
    def test_creates_sange_skeleton(
        self, runner: CliRunner, tmp_path: Path
    ) -> None:
        result = runner.invoke(app, ["init", "--repo", str(tmp_path)])
        assert result.exit_code == 0, result.output
        assert (tmp_path / ".sange").is_dir()
        assert (tmp_path / ".sange" / "commits").is_dir()
        assert (tmp_path / ".sange" / "telemetry").is_dir()

    def test_creates_makefile_shim(
        self, runner: CliRunner, tmp_path: Path
    ) -> None:
        runner.invoke(app, ["init", "--repo", str(tmp_path)])
        makefile = tmp_path / "Makefile"
        assert makefile.is_file()
        content = makefile.read_text()
        assert "Auto-generated by Sange" in content
        assert ".sange/makefiles/" in content

    def test_creates_makefile_fragments(
        self, runner: CliRunner, tmp_path: Path
    ) -> None:
        runner.invoke(app, ["init", "--repo", str(tmp_path)])
        mk_dir = tmp_path / ".sange" / "makefiles"
        assert (mk_dir / "_core" / "help.mk").is_file()
        assert (mk_dir / "_core" / "env.mk").is_file()
        assert (mk_dir / "_core" / "colors.mk").is_file()
        assert (mk_dir / "vcs" / "git.mk").is_file()
        assert (mk_dir / "lang" / "python.mk").is_file()

    def test_creates_gitignore(
        self, runner: CliRunner, tmp_path: Path
    ) -> None:
        runner.invoke(app, ["init", "--repo", str(tmp_path)])
        gi = tmp_path / ".gitignore"
        assert gi.is_file()
        text = gi.read_text()
        assert "/Makefile" in text
        assert "/.sange/commits/" in text
        assert "/.sange/telemetry/" in text


# --------------------------------------------------------------------------- #
# Idempotency
# --------------------------------------------------------------------------- #


class TestIdempotent:
    def test_re_run_does_not_overwrite(
        self, runner: CliRunner, tmp_path: Path
    ) -> None:
        runner.invoke(app, ["init", "--repo", str(tmp_path)])
        # User edits the Makefile.
        makefile = tmp_path / "Makefile"
        makefile.write_text("# user-edited\n")

        # Re-run init without --force.
        result = runner.invoke(app, ["init", "--repo", str(tmp_path)])
        assert result.exit_code == 0
        assert makefile.read_text() == "# user-edited\n"
        assert "skipped" in result.output

    def test_re_run_does_not_double_gitignore(
        self, runner: CliRunner, tmp_path: Path
    ) -> None:
        runner.invoke(app, ["init", "--repo", str(tmp_path)])
        gitignore_first = (tmp_path / ".gitignore").read_text()
        runner.invoke(app, ["init", "--repo", str(tmp_path)])
        gitignore_second = (tmp_path / ".gitignore").read_text()
        # Bytes must be identical on the second run.
        assert gitignore_first == gitignore_second

    def test_re_run_repairs_missing_dir(
        self, runner: CliRunner, tmp_path: Path
    ) -> None:
        runner.invoke(app, ["init", "--repo", str(tmp_path)])
        # Operator manually nukes .sange/telemetry.
        import shutil

        shutil.rmtree(tmp_path / ".sange" / "telemetry")
        # Re-init heals.
        result = runner.invoke(app, ["init", "--repo", str(tmp_path)])
        assert result.exit_code == 0
        assert (tmp_path / ".sange" / "telemetry").is_dir()


# --------------------------------------------------------------------------- #
# --force
# --------------------------------------------------------------------------- #


class TestForce:
    def test_force_overwrites_makefile(
        self, runner: CliRunner, tmp_path: Path
    ) -> None:
        runner.invoke(app, ["init", "--repo", str(tmp_path)])
        makefile = tmp_path / "Makefile"
        makefile.write_text("# stale\n")

        result = runner.invoke(
            app, ["init", "--repo", str(tmp_path), "--force"]
        )
        assert result.exit_code == 0
        assert "Auto-generated by Sange" in makefile.read_text()

    def test_force_overwrites_fragments(
        self, runner: CliRunner, tmp_path: Path
    ) -> None:
        runner.invoke(app, ["init", "--repo", str(tmp_path)])
        frag = tmp_path / ".sange" / "makefiles" / "_core" / "help.mk"
        frag.write_text("# stale\n")

        runner.invoke(app, ["init", "--repo", str(tmp_path), "--force"])
        assert "# stale" not in frag.read_text()


# --------------------------------------------------------------------------- #
# Flag opt-outs
# --------------------------------------------------------------------------- #


class TestOptOuts:
    def test_no_makefile_skips_kit(
        self, runner: CliRunner, tmp_path: Path
    ) -> None:
        result = runner.invoke(
            app, ["init", "--repo", str(tmp_path), "--no-makefile"]
        )
        assert result.exit_code == 0
        assert not (tmp_path / "Makefile").exists()
        assert not (tmp_path / ".sange" / "makefiles").exists()
        # Skeleton + gitignore still happen.
        assert (tmp_path / ".sange" / "commits").is_dir()

    def test_no_gitignore_skips_gitignore(
        self, runner: CliRunner, tmp_path: Path
    ) -> None:
        result = runner.invoke(
            app, ["init", "--repo", str(tmp_path), "--no-gitignore"]
        )
        assert result.exit_code == 0
        assert not (tmp_path / ".gitignore").exists()


# --------------------------------------------------------------------------- #
# Gitignore preservation
# --------------------------------------------------------------------------- #


class TestGitignorePreservation:
    def test_appends_to_existing_gitignore(
        self, runner: CliRunner, tmp_path: Path
    ) -> None:
        (tmp_path / ".gitignore").write_text("*.pyc\n.env\n")
        runner.invoke(app, ["init", "--repo", str(tmp_path)])
        text = (tmp_path / ".gitignore").read_text()
        # User entries preserved.
        assert "*.pyc" in text
        assert ".env" in text
        # Sange entries added.
        assert "/Makefile" in text
        assert "/.sange/commits/" in text

    def test_gitignore_already_has_some_entries(
        self, runner: CliRunner, tmp_path: Path
    ) -> None:
        # User already has /Makefile; init should only add the missing two.
        (tmp_path / ".gitignore").write_text("/Makefile\n")
        runner.invoke(app, ["init", "--repo", str(tmp_path)])
        text = (tmp_path / ".gitignore").read_text()
        # /Makefile appears exactly once.
        assert text.count("/Makefile") == 1
        assert "/.sange/commits/" in text


# --------------------------------------------------------------------------- #
# Error path
# --------------------------------------------------------------------------- #


class TestErrors:
    def test_nonexistent_repo_exits_2(
        self, runner: CliRunner, tmp_path: Path
    ) -> None:
        result = runner.invoke(
            app, ["init", "--repo", str(tmp_path / "nonexistent")]
        )
        assert result.exit_code == 2
        assert "not a directory" in result.output


# --------------------------------------------------------------------------- #
# JSON mode
# --------------------------------------------------------------------------- #


class TestJsonMode:
    def test_json_emits_action_log(
        self, runner: CliRunner, tmp_path: Path
    ) -> None:
        result = runner.invoke(
            app, ["--json", "init", "--repo", str(tmp_path)]
        )
        assert result.exit_code == 0
        payload = json.loads(result.output)
        assert payload["repo"] == str(tmp_path.resolve())
        assert isinstance(payload["actions"], list)
        # Every action has kind + status keys.
        for a in payload["actions"]:
            assert "status" in a

    def test_json_idempotent_run_shows_skipped(
        self, runner: CliRunner, tmp_path: Path
    ) -> None:
        runner.invoke(app, ["init", "--repo", str(tmp_path)])
        result = runner.invoke(
            app, ["--json", "init", "--repo", str(tmp_path)]
        )
        payload = json.loads(result.output)
        statuses = [a["status"] for a in payload["actions"]]
        assert "skipped" in statuses or "exists" in statuses
        assert "already-present" in statuses


# --------------------------------------------------------------------------- #
# Integration with `sange doctor`
# --------------------------------------------------------------------------- #


class TestIntegrationWithDoctor:
    def test_after_init_doctor_makefile_check_passes(
        self, runner: CliRunner, tmp_path: Path
    ) -> None:
        """After `sange init`, the Makefile is gitignored — but it's
        not in a git repo yet, so the doctor check skips it (passes).
        This is the realistic post-init state before `git add`."""

        from sange.cli.doctor import _check_makefile_tracked

        runner.invoke(app, ["init", "--repo", str(tmp_path)])
        result = _check_makefile_tracked(tmp_path)
        assert result.ok is True
